# Generated by Django 5.2.4 on 2025-08-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
